# Site settings
title: Nynim.org
email: tony@nynim.org
description: >
  Tony Duckles on programming, photography, and general geekery
baseurl: ""
url: "http://nynim.org"
date_format: "%b %-d, %Y"

# Google services
google_analytics: UA-6748678-1

# Disqus post comments
disqus_shortname: nynim

# Social icons
github_username:  tonyduckles
twitter_username: tonyduckles

# Octopress 2-style excerpts
excerpt_separator: "<!-- more -->"
excerpt_link: "Read more &rarr;"

# Build settings
markdown: kramdown
theme: minima
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]  # Disable smart-quotes
permalink: /blog/:year/:month/:day/:title/  # Octopress 2-style permalink
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE.txt
  - docker-compose.yml
