# Site settings
title: Nynim.org
email: tony@nynim.org
author: Tony Duckles
description: >
  Tony Duckles on programming, photography, and general geekery
baseurl: ""
url: "http://nynim.org"
date_format: "%b %-d, %Y"
header_pages:
 - blog/index.html
 - blog/archives.html
 - code.md
 - guitar-tabs.html
 - about.md
show_post_footers: true
collections:
  code:
    output: true
  guitar-tabs:
    output: true

# Optional features
show_social_icons: true

# Google services
google_analytics: UA-6748678-1

# Disqus post comments
disqus_shortname: nynim

# Social icons
github_username: tonyduckles
twitter_username: tonyduckles
instagram_username: tonyduckles
lastfm_username: tonyduckles
pinboard_username: tduckles
linkedin_username: tonyduckles
flickr_username: tonyduckles

# UI Text
text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'Contact message from Nynim.org'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Octopress 2-style excerpts
excerpt_separator: "<!-- more -->"
excerpt_link: "Read on &rarr;"

# Linkblog (external-url)
linkblog:
  permalink_label: "&#8734;"
  permalink_label_feed: "&#9875; Permalink"
  linkpost:
    marker: "&rarr;"

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]  # Disable smart-quotes
permalink: /blog/:year/:month/:day/:title/  # Octopress 2-style permalink
paginate: 10
paginate_path: "/blog/page/:num"
category_dir: "blog/categories"
sass:
  style: compressed
include:
  - .htaccess
  - .nojekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - script/
  - vendor/
  - LICENSE.txt
  - README.md
  - docker-compose.yml
