version: '3'
services:
  jekyll:
    image: jekyll/jekyll:3.8
    environment:
      BUNDLE_PATH: /srv/jekyll/vendor/bundle
    ports:
      - 4000:4000
      - 4444:4444
    volumes:
      - .:/srv/jekyll
