version: '2'
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --incremental
    ports:
      - 4000:4000
      - 4444:4444
    volumes:
      - .:/srv/jekyll
    container_name: jekyll
